CREATE DATABASE EVA_PROINTEL;

USE EVA_PROINTEL;

CREATE TABLE [user](
	idUser VARCHAR(44) NOT NULL PRIMARY KEY,
	nameUser VARCHAR(250) NOT NULL,
	lastNameUser VARCHAR(250) NOT NULL,
	age INT NOT NULL,
	statusUser VARCHAR(1) NOT NULL,
	createDate DATETIME NOT NULL,
	updateDate DATETIME
);

CREATE TABLE [task](
	idTask VARCHAR(44) NOT NULL PRIMARY KEY,
	nameTask VARCHAR(250) NOT NULL,
	descriptionTask VARCHAR(400) NOT NULL,
	priorityTask VARCHAR(250) NOT NULL,
	dateLimit DATETIME NOT NULL,
	statusTask VARCHAR(250) NOT NULL,
	createDate DATETIME NOT NULL,
	updateDate DATETIME
);

CREATE TABLE [task_user_asigned](
	idAsignation INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	idTask VARCHAR(44) NOT NULL,
	idUser VARCHAR(44) NOT NULL,
	statusTaskUser VARCHAR(1) NOT NULL,
	createDate DATETIME NOT NULL,
	updateDate DATETIME
);